# Site settings
title: ProjectMSAD
description: > # this means to ignore newlines until "baseurl:"
  The kind of person who prefers plane tickets over cats.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "project-msad.herokuapp.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
